### ISSUE TITLE
Possible gap in option handling

### ISSUE THREAD

**Issue by PatrickDRusk** [amancevice/envopt#3]
It is possible to have a docstring like the following:

``` Bash
foo.py (--opt1 | --opt2)
```

The intent of the above would be "you must specify one and only one option between opt1 and opt2". docopt properly prints a usage statement unless one and only one is specified on the command line.

It seems like the following should potentially work in envopt, but they don't:

``` Bash
OPT1=true foo.py
OPT2=true foo.py
```

It also seems like the following _shouldn't_ be allowed, but it is:

``` Bash
OPT1=true OPT2=true foo.py --opt1
```

In the dict resulting from `envopt.envopt(__doc__)`, it would show _both_ '--opt1' and '--opt2' as True.

It may be beyond the ambition of envopt to handle these situations, and I am not held up by them (because I can make a boolean switch option), but I thought I would mention it. :)

**Comment by amancevice** [comment]
this is sort of a [docopt](https://github.com/docopt/docopt) question, but I think you could accomplish this by supplying two usage lines:

```
Usage:
    foo.py --opt1
    foo.py --opt2
```

I think that if you supplied an ENV value for both OPT1 and OPT2 you would get a usage error, so I don't know if this is a good solution for your use case. If it's really true that only one should be used, perhaps it would be better to a) split the script into 2 distinct use cases, b) not supply these values in the environment but force the user to choose at run time

**Comment by PatrickDRusk** [comment]
Sorry if I wasn't clear, but docopt does handle the docstring I specified. My point was that envopt doesn't give you the ability to specify which option was chosen by using an environment variable instead.

With a subsequent test, I have further determined that if you have any required options, they can't be supplied via environment variables. For instance, if I have:

``` Bash
"""
test-envopt

Usage:
    test-envopt.py --opt1=VAL
"""
import envopt

if __name__ == '__main__':
    args = envopt.envopt(__doc__)
    print(args)
```

...I can't say...

``` Bash
OPT1=blah python test_envopt.py 
```

It appears that the doctopt handing of the required parameters is not augmented by checking to see if it was supplied by an environment variable.

**Comment by amancevice** [comment]
I can see how you could consider this a bug, but I'm going to argue why it isn't & that I think it's a misuse of `envopt` to use it this way. I think the miscommunication is that you are using the tool as if it is supposed to simulate a terminal command; in reality it is a tool to add default values to the `__doc__` of a Python script.

This is useful in the case where you are writing a script that _could_ have sensible defaults, but wish to shift the burden of those defaults from being hardcoded in the script to the environment of the deployment location.

If you are writing a script that has arguments, they can be either _required_ or _optional_, but not both. If an argument is **required** in the `Usage:` section of a docopt script, then you are saying "every time this script is invoked the user _must_ pass this option/flag." This implies there can **never** be a default value, and so it becomes inappropriate to use `envopt`.

I think if you start thinking of `envopt` in this way -- injecting strings into the pydoc and nothing more -- then you will be better served by it.

**Comment by amancevice** [comment]
In case it wasn't clear -- you are not required to set `ENV` values for _all_ the options you define in the pydoc; just define the ones who need deployment-specific defaults.

One of the advantages of `envopt` working this way is that you can use the `--help` flag of a script to actually _see_ the deployed defaults. 

In other words, if I change your above script to:

``` python
"""
test-envopt

Usage:
    test-envopt.py [options]

Options:
    --opt1 VAL  # fizzbuzz
"""

import envopt

if __name__ == '__main__':
    args = envopt.envopt(__doc__)
    print(args)
```

where `--opt1` is now optional, and I execute:

``` bash
OPT1=foo python tmp/test-envopt.py --help
```

I see:

```
test-envopt

Usage:
    test-envopt.py [options]

Options:
    --opt1 VAL  # Hello World [default: foo]
```

Notice the default value injected into the pydoc.

**Comment by PatrickDRusk** [comment]
Well, as I noted in my original comment, "it may be beyond the ambition of envopt to handle these situations". :)
